name: "Language-Manager"
version: "1.0"
author: "xxAROX"
website: "https://github.com/HQGames/Language-Manager"
description: "Language-Manager by xxAROX."

api:
  - "4.0.0"
main: HQGames\LanguageManager\LanguageManager